lr: 3e-4
ent_coef: 0.1
max_grad_norm: 0.5
num_envs: 64
num_steps: 64
num_inner_update: 1000
num_outer_update: 10
num_epoch: 4       # gradient epochs per collected batch (with IS correction)
gamma: 1.0         # time-discount factor
eta: 0.2           # entropy regularization coefficient
c_vtrace: 1.0      # importance sampling clip for V-trace targets
nerd_clip: 100.0   # advantage clipping bound for NERD
nerd_beta: 2.0     # logit threshold for NERD force application
